### ISSUE TITLE
Make test for autogf.py

### ISSUE THREAD

**Issue by kallstadt-usgs** [usgs/groundfailure#102]

**Comment by kallstadt-usgs** [comment]
Need to update gfail_test.py so it tests multiple models for webpage creation. Also need to make it so it won't crash if only one model is run (flexibly handles missing models/null events)

**Comment by emthompson-usgs** [comment]
Note that I named [this](https://github.com/usgs/groundfailure/blob/master/tests/gfail_test.py#L69) test inaccurately as "test_zhu2015_web". I think I named it that way because I originally wrote it to only include Zhu 2015, but then I changed it to include all of the models in [this](https://github.com/usgs/groundfailure/blob/master/tests/data/test_conf) conf file.
